/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface MizuchiOracleInterface extends utils.Interface {
  functions: {
    "estimateAggregator(address)": FunctionFragment;
    "estimateOut(address,address,address,uint128,uint24,uint32)": FunctionFragment;
    "factory()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "estimateAggregator" | "estimateOut" | "factory"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "estimateAggregator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateOut",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "estimateAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;

  events: {};
}

export interface MizuchiOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MizuchiOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    estimateAggregator(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { price: BigNumber }>;

    estimateOut(
      token0: string,
      token1: string,
      tokenIn: string,
      amountIn: BigNumberish,
      fee: BigNumberish,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    factory(overrides?: CallOverrides): Promise<[string]>;
  };

  estimateAggregator(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  estimateOut(
    token0: string,
    token1: string,
    tokenIn: string,
    amountIn: BigNumberish,
    fee: BigNumberish,
    secondsAgo: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  factory(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    estimateAggregator(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateOut(
      token0: string,
      token1: string,
      tokenIn: string,
      amountIn: BigNumberish,
      fee: BigNumberish,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    estimateAggregator(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateOut(
      token0: string,
      token1: string,
      tokenIn: string,
      amountIn: BigNumberish,
      fee: BigNumberish,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    estimateAggregator(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimateOut(
      token0: string,
      token1: string,
      tokenIn: string,
      amountIn: BigNumberish,
      fee: BigNumberish,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
